USERNAME = 'lakehousepi@gmail.com'
PASSWORD = 'lakehousepi!'
SERVERNAME = 'smtp.gmail.com:587'

SPREADSHEET_NAME = 'LHD'
SPREADSHEETKEY = '19f3JV1XrAOgctY5ON41cwIEDjB1WQOH5b7W-xu8FHA8'
WORKSHEETID = '0'